apiVersion: v1
kind: ServiceAccount
metadata:
 name: app-sa
 namespace: default
 annotations:
   eks.amazonaws.com/role-arn:  <IAM Role for service account>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      serviceAccountName: app-sa
      initContainers:
      - image: amazon/aws-cli
        name: my-aws-cli
        command: ['aws', 's3', 'ls']
      containers:
      - image: nginx
        name: sample-app
        ports:
        - containerPort: 8080
          name: sample-app
